server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: campus-service
        uri: lb://campus-service
        predicates:
        - Path=/campussrvc/**
        filters:
        - RewritePath=/campus/(?<path>.*), /$\{path}
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employeesrvc/**
        filters:
        - RewritePath=/campus/(?<path>.*), /$\{path}
      - id: search-service
        uri: lb://search-service
        predicates:
        - Path=/searchsrvc/**
        filters:
        - RewritePath=/campus/(?<path>.*), /$\{path}
      - id: documentation-service
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs