server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  cloud:
    gateway:
      routes:
        - id: campus-service
          uri: http://localhost:10001
          predicates:
          - Path=/campus/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
          - Path=/employee/**
        - id: search-service
          uri: lb://search-service
          predicates:
          - Path=/search/**