server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
#            allowed-headers:
#              - Content-Type
#            allowed-methods:
#              - "GET"
#              - POST
#              - PUT
#              - PATCH
#              - DELETE
      routes:
      - id: campus-service
        uri: lb://campus-service
        predicates:
        - Path=/campuses/**
        filters:
        - RewritePath=/campus/(?<path>.*), /$\{path}
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employees/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      - id: search-service
        uri: lb://search-service
        predicates:
        - Path=/search/**
        filters:
        - RewritePath=/search/(?<path>.*), /$\{path}
