server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://ec2co-ecsel-1kkd7h5x8iddx-1154184150.us-east-1.elb.amazonaws.com:8888/*"
            allowed-headers:
              - "Content-Type, text/plain"
              - "Accept"
              - "Content-Language"
            allowed-methods:
              - "*"
      routes:
      - id: campus-service
        uri: lb://campus-service
        predicates:
        - Path=/campus/**
        filters:
        - RewritePath=/campus/(?<path>.*), /$\{path}
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      - id: search-service
        uri: lb://search-service
        predicates:
        - Path=/search/**
        filters:
        - RewritePath=/search/(?<path>.*), /$\{path}