server:
  port: 8080

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCO_URL:localhost}:${SERVICE_DISCO_PORT:8761}/eureka
    fetch-registry: true
    register-with-eureka: true


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: campus-service
          uri: lb://campus-service
          predicates:
            - Path=/campuses/**
          filters:
            - RewritePath=/campus/(?<path>.*), /$\{path}
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/(?<path>.*), /$\{path}
      globalcors:
        cors-configuration:
          '/**':
            allowed-origins:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
