server:
  port: 10000

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${SERVICE_DISCO_URL:localhost}:${SERVICE_DISCO_PORT:8761}/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  mongodb:
    embedded:
      version: 2.2.0
  data:
    mongodb:
      repositories:
        enabled: true